//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdChimeProejctEntities : DbContext
    {
        public AdChimeProejctEntities()
            : base("name=AdChimeProejctEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<panelContact> panelContacts { get; set; }
        public virtual DbSet<panelContactsVariable> panelContactsVariables { get; set; }
        public virtual DbSet<tCampaign> tCampaigns { get; set; }
        public virtual DbSet<tCampaignSend> tCampaignSends { get; set; }
        public virtual DbSet<tRecipientNumber> tRecipientNumbers { get; set; }
        public virtual DbSet<tRecipientSm> tRecipientSms { get; set; }
        public virtual DbSet<tTemplateSm> tTemplateSms { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tVarContact> tVarContacts { get; set; }
        public virtual DbSet<sLink> sLinks { get; set; }
        public virtual DbSet<tSMSCounter> tSMSCounters { get; set; }
    }
}
