//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class panelContactsVariable
    {
        public int idlig { get; set; }
        public Nullable<int> idContact { get; set; }
        public Nullable<int> idVar { get; set; }
        public string sValue { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string updatedbyuser { get; set; }
    
        public virtual panelContact panelContact { get; set; }
        public virtual tVarContact tVarContact { get; set; }
    }
}
