//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class sLink
    {
        public int idlink { get; set; }
        public string sOriginalLink { get; set; }
        public string sShorterLink { get; set; }
    }
}
