//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCampaignSend
    {
        public int idEnvioEmail { get; set; }
        public Nullable<int> idcampaing { get; set; }
        public string tEmailtoGroup { get; set; }
        public Nullable<int> idrecipient { get; set; }
        public Nullable<bool> bSucess { get; set; }
        public Nullable<int> nEnvio { get; set; }
        public Nullable<System.DateTime> sDatetoSend { get; set; }
        public string sSendbyWho { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<int> idlink { get; set; }
        public string sShorterLink { get; set; }
    
        public virtual tCampaign tCampaign { get; set; }
        public virtual tRecipientSm tRecipientSm { get; set; }
    }
}
