//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCampaign()
        {
            this.tCampaignSends = new HashSet<tCampaignSend>();
        }
    
        public int idcampaign { get; set; }
        public string TitleCampaing { get; set; }
        public string Description { get; set; }
        public string Sender { get; set; }
        public string Text { get; set; }
        public Nullable<int> idtemplate { get; set; }
        public Nullable<int> idrecipient { get; set; }
        public Nullable<System.DateTime> sendDate { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string updatedbyuser { get; set; }
    
        public virtual tRecipientSm tRecipientSm { get; set; }
        public virtual tTemplateSm tTemplateSm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCampaignSend> tCampaignSends { get; set; }
    }
}
