//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdChimeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRecipientNumber
    {
        public int idrecipientnumber { get; set; }
        public Nullable<int> idrecipient { get; set; }
        public Nullable<int> idContact { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
    
        public virtual panelContact panelContact { get; set; }
        public virtual tRecipientSm tRecipientSm { get; set; }
    }
}
