// <auto-generated />
namespace AdChimeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changes_20221226_1638 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_20221226_1638));
        
        string IMigrationMetadata.Id
        {
            get { return "202212261639462_changes_20221226_1638"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
